# shellcheck disable=SC2148
FROM opensuse/tumbleweed@sha256:8b3445ed63e245be4d7cca38de5f4d95d29e19b2987cf5338aae25a8367d9587

RUN zypper refresh && \
    zypper addrepo https://download.opensuse.org/repositories/openSUSE:Tools/openSUSE_Tumbleweed/openSUSE:Tools.repo && \
    zypper --gpg-auto-import-keys refresh && \
    zypper install -y osc build git curl wget && \
    zypper clean -a

WORKDIR /workspace

CMD ["/bin/bash"]